name: Build ALEAPP executables and generate release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package ALEAPP
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: aleapp.spec
        
    - name: Package ALEAPP GUI
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: aleappGUI.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ALEAPP
        path: dist/windows
        
    - name: Zip All The Things
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r dist/ALEAPP-windows.zip dist/windows
        
    - name: Create Github Release
      id: githubrelease
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.githubrelease.outputs.upload_url }}
        asset_path: dist/ALEAPP-windows.zip
        asset_name: ALEAPP-windows.zip
        asset_content_type: application/zip